### ISSUE TITLE
寻求一个Federated meta learning 的内容实现

### ISSUE THREAD

**Issue by littleso-so** [ChengtaiCao/Paper#1]
您好，我最近阅读了Federated meta-learning for recommendation这篇论文，但是在复现其内容的时候遇到了一些问题，想冒昧地问一下您有没有尝试过实现该论文呢，如果有的话，方便把代码发给我参考一下吗？谢谢！

**Comment by ChengtaiCao** [comment]
很抱歉，由于后面没有继续深入研究推荐，所以也没有复现该篇论文

**Comment by littleso-so** [comment]
嗯嗯好，还是很感谢！
在2019年06月03日 17:43，ChengtaiCao 写道：

很抱歉，由于后面没有继续深入研究推荐，所以也没有复现该篇论文
