### ISSUE TITLE
请问您有Selective Experience Replay for Lifelong Learning这篇论文的附录吗，谢谢！

### ISSUE THREAD

**Issue by climbL** [ChengtaiCao/Paper#2]
Do you have the appendix to the paper Selective Experience Replay for Lifelong Learning？
Could you share the appendix with me if you have it? Thank you!!
I almost searched the entire network but couldn't find it......

请问您有论文Selective Experience Replay for Lifelong Learning的附录吗？
如果有的话，您可以和我分享一下吗？ 谢谢！！
我几乎找遍了整个网络也没有找到...

**Comment by ChengtaiCao** [comment]
Sorry，I don't have either.
